apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitlab-adapter-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: gitlab-adapter-v1
        version: v1
    spec:
      containers:
      - name: gitlab-adapter-v1
        image: consortit-docker-cme-local.jfrog.io/gitlab-adapter:image-version
        ports:
          - containerPort: 8080
          - containerPort: 8081
        env:
          - name: gitlab_personal_access_token
            valueFrom:
              secretKeyRef:
                name: gitlab-adapter-secret
                key: gitlab_personal_access_token
          - name: gitlab_hosts
            valueFrom:
              secretKeyRef:
                name: gitlab-adapter-secret
                key: gitlab_hosts
          - name: token_scope
            valueFrom:
              secretKeyRef:
                name: gitlab-adapter-secret
                key: token_scope
          - name: jwk_kid
            valueFrom:
              secretKeyRef:
                name: gitlab-adapter-secret
                key: jwk_kid
          - name: jwk_url
            value: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M4FyC0JPA/.well-known/jwks.json
          - name: jwk_alg
            value: RS256
          - name: appversion
            value: "0.1"
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-adapter-v1
  labels:
    application: gitlab-adapter-v1
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: external
    - port: 81
      protocol: TCP
      targetPort: 8081
      name: health
  selector:
    application: gitlab-adapter-v1
    version: v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-adapter-v1
  labels:
    application: gitlab-adapter-v1
    version: v1
spec:
  rules:
   - host: "cme.dev.k8s.consort-it.de"
     http:
      paths:
      - path: /api/v1/gitlab-adapter
        backend:
          serviceName: gitlab-adapter-v1
          servicePort: 80
      - path: /api/v1/gitlab-adapter/health
        backend:
          serviceName: gitlab-adapter-v1
          servicePort: 81